## A basic GitHub Actions workflow for your Quarkus application.

name: CI

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

env:
  QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
  QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKER_HUB_PWD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
        
      - name: Increment version and create tag
        run: |
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          IFS='.' read -r major minor patch <<< "${LAST_TAG#v}"
          NEW_PATCH=$((patch + 1))
          NEW_TAG="v$major.$minor.$NEW_PATCH"
          git tag $NEW_TAG
          git push origin $NEW_TAG
      # - name: Build
      #   run: |
      #     ./mvnw package -B -Dquarkus.container-image.tag=${GITHUB_REF##*/}
      #     docker image ls
